# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      java: amazon-corretto-21
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 820183542087.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=820183542087.dkr.ecr.$AWS_REGION.amazonaws.com/user-post-api-project
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running tests..."
      - ./mvnw test
      - echo "Packaging application..."
      - ./mvnw package
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker images to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG